### ISSUE TITLE
Notifications reappear after acknowledge all

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#107]
**Steps to Reproduce**
* Run a tale
* Notification window appears
* Wait for tale to start completely
* Click "Acknowledge all"
* Wait

This happens to me for every tale I build or run, every time.

**Expected Results**
Notification window does not reappear unless there is a new notification

**Actual Results**
Notification window appears displaying dismissed notifications

**NOTES**
* MacOS, Chrome 86.0.4240.75
* `lastRead` value is updated in local storage, but appears to be unused.
* Network indicates call to `https://girder.local.wholetale.org/api/v1/notification/stream?timeout=30&lastEventId=&r=8901482285531686`, but the Girder notification/stream API has only `timeout` and `since` parameters. I don't know where `lastEventId` and `r` are coming from.

**Comment by craig-willis** [comment]
Just noting that I continue to see this and it's very disruptive. Locally, I've made a change to disable showing the notification panel with each new notification.

**Comment by bodom0015** [comment]
Fixed by #129
