### ISSUE TITLE
View Logs gives 403 for image build logs

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/ngx-dashboard#109]
**Steps to Reproduce**
1. Create a Tale
2. Launch Tale
3. Wait for notification stream to appear
4. Click "View Logs"

**Expected Results**
View Logs modal shows appears, and offers log output from repo2docker build

**Actual Results**
View Logs modal appears, but is blank. Debug console shows a 403 error:
```json
{
  "message": "Read access denied for job 5fb2bd8a39efbf30754c56fd (user 5f887c6a81d63263a60a657f).",
  "type": "access"
}
```

**Comment by Xarthisius** [comment]
Can you login to girder as admin and check who owns that job? I'm testing something right now with fresh build and cannot reproduce it.

**Comment by bodom0015** [comment]
Perhaps this is a side-effect of importing via Git? (see #54) I thought it was a more general problem, but maybe just 

As the admin, performing a GET /job does not include a job with this ID, although the mentioned job ID _is_ a `parentID` for the "Create Tale volume" task. Performing a `GET /job/` yields a Tale with a `null` parentID, but offering no other indication of where the job came from:
```
{
  "_accessLevel": 2,
  "_id": "5fb2bd8a39efbf30754c56fd",
  "_modelType": "job",
  "args": [
    "5fb2bd8439efbf30754c56f2",
    false
  ],
  "async": false,
  "celeryTaskId": "f5d02a96-8c5e-4204-b0b7-10aee0fa5870",
  "created": "2020-11-16T17:57:30.329000+00:00",
  "handler": "celery_handler",
  "interval": 0,
  "jobInfoSpec": {
    "headers": {
      "Girder-Token": "0fDNs68IXr8GybxLwfsSEmIWFiUSMocGXq1c2ImHInEkCIKpVUffy1TdmcmFopjs"
    },
    "logPrint": true,
    "method": "PUT",
    "reference": "5fb2bd8a39efbf30754c56fd",
    "url": "http://girder:8080/api/v1/job/5fb2bd8a39efbf30754c56fd"
  },
  "kwargs": {},
  "log": [
    "",
    "...Truncated for sanity reasons...",
    "\n{\"progressDetail\":{},\"aux\":{\"Tag\":\"latest\",\"Digest\":\"sha256:2b0951853648947904452de06d12da5be6d5c1ba5303be44819d0e1088948ccb\",\"Size\":8270}}\r\n\n",
    "",
    ""
  ],
  "meta": {},
  "parentId": null,
  "progress": {
    "current": 2,
    "message": "Image build succeeded",
    "notificationId": null,
    "total": 2
  },
  "public": false,
  "status": 3,
  "timestamps": [
    {
      "status": 2,
      "time": "2020-11-16T17:57:30.348000+00:00"
    },
    {
      "status": 3,
      "time": "2020-11-16T17:59:04.582000+00:00"
    }
  ],
  "title": "Build Tale Image",
  "type": "celery",
  "updated": "2020-11-16T17:59:04.612000+00:00",
  "when": "2020-11-16T17:57:30.329000+00:00"
}
```

**Comment by Xarthisius** [comment]
Looks like the only way of finding a job owner is via `girder-shell`:

```python
>>> from girder.plugins.jobs.models.job import Job
>>> Job().load("5fb2bd8a39efbf30754c56fd", force=True)["access"]["users"][0]
```

**Comment by bodom0015** [comment]
Can't seem to reliably recreate this. It seems to come up sometimes during certain Git import cases.

Will take note and close for now, and can reopen if this resurfaces again
