### ISSUE TITLE
'Files' tab div overflows on small workspaces/external data

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/ngx-dashboard#115]
The gist is that, when the file list is short, its div will overrun the outer div. When the file listing is _full_, the file list container doesn't expand past the outer div. I gave an extreme version of manually squishing the page, but I noticed it while using Firefox which has a larger page than Chrome.

**Steps to Reproduce**

Case 1:
1. Open a Tale
2. Navigate to the 'Files' tab
3. Make sure that there are few enough files to keep the scrollbar from showing
3. Resize the window, length wise to squish the page

Case 2:
1. Open a Tale
2. Add files to fill up the window
3. Resize the window, length wise to squish the page

**Expected Results**

Case 1: The div stays within the outer div

Case 2: These results were expected (no overflow, the scroll bar gets smaller as the window gets smaller)

**Actual Results**

Case 1: In this case the container holding the file ran over its container.

<img width="1637" alt="Screen Shot 2020-12-21 at 1 43 30 PM" src="https://user-images.githubusercontent.com/9289652/102825037-ddc69f80-4392-11eb-9718-b5fc3a70d897.png">

Case 2: In this case the container holding the files expanded out to its container, which expanded with it.
<img width="1640" alt="Screen Shot 2020-12-21 at 1 43 44 PM" src="https://user-images.githubusercontent.com/9289652/102825048-e15a2680-4392-11eb-819f-21ff7a9b5ef8.png">

**NOTES**

Tested in both Chrome and Firefox

**Comment by Xarthisius** [comment]
I believe this was fixed during footer reorg.
