### ISSUE TITLE
Interact page does not handle "iframe=false" case

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#116]
I ran into this while testing a new environment that cannot be displayed in an iframe. 

**Steps to Reproduce**
* Modify `setup_girder.py` or use `girder-shell` in the `girder` container to set `iframe=False` for an image
* Create a tale using that image and run it

**Expected Results**
Per the old dashboard behavior (https://github.com/whole-tale/dashboard/blob/master/app/components/ui/tale-tab-interact/template.hbs#L1-L16) a message is displayed indicating that the interactive environment must be opened in a separate browser window.

**Actual Results**
No message is displayed and iframe support is assumed.

**Comment by bodom0015** [comment]
There is supposed to be handling for this within `tale.interact` already, but I haven't actually seen it work since our test environments use `iframe=True`:
https://github.com/whole-tale/ngx-dashboard/blob/master/src/app/%2Brun-tale/run-tale/tale-interact/tale-interact.component.html#L12-L19

**Comment by craig-willis** [comment]
It looks like this was a misunderstanding on my part.  I thought I could change the `iframe` value on the image after the tale was created to effect the instance. It ends up that the `iframe` value is copied to the tale during tale creation, so to test I had to change the image value before creating the tale.

**Revised test steps:**
* `make dev`
* Use `girder-shell` to change the iframe value to False for JupyterLab
```
$ docker exec -ti $(docker ps --filter=name=wt_girder -q) base
# girder-shell
gs>  from girder.plugins.wholetale.models.image import Image
         img = Image().findOne({"name": "JupyterLab"})
         img["iframe"] = False
         Image().save(img)
```
* Create a new JupyterLab tale and run it

I'm seeing what I expected to see:
<img width="922" alt="Screen Shot 2021-01-25 at 3 29 33 PM" src="https://user-images.githubusercontent.com/4334350/105762241-25a48d80-5f22-11eb-8221-d54bf8cdf16b.png">

**Comment by craig-willis** [comment]
Not a bug.

**Comment by bodom0015** [comment]
The styling is gross for this case, so a PR still incoming :+1:
