### ISSUE TITLE
Integrating versioning and sharing

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#119]
With https://github.com/whole-tale/girder_wholetale/pull/434 versions are now appearing for users a tale is shared with.  This introduces a few issues:
* User with view permissions should not be able to rename or delete a version
* Less important, it might be useful to display the name the user who created a version

**Comment by bodom0015** [comment]
What other version-related functions require permissions, and which permissions are required?

Proposing the following initially:
* Create a new version >= Write
* Rename a version >= Write
* Delete a version >= Admin

Any objections, or anything else that might be missing?
