### ISSUE TITLE
[Draft] Start recorded run

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#123]
**Requirements:**
* User creates and selects a run configuration (https://github.com/whole-tale/ngx-dashboard/issues/122)
* User selects "Recorded Run"
* A run is submitted via `POST /run` API (https://github.com/whole-tale/girder_wholetale/issues/493)
* Run progress is displayed via notifications panel

**Mockups:**
* https://whole-tale.github.io/wholetale-css-mockup/src/run-meta.html
* Select versions icon

**Comment by bodom0015** [comment]
This PR adds the `/run/:id/start` endpoint: https://github.com/whole-tale/wt_versioning/pull/29
