### ISSUE TITLE
'External Data' doesn't update when navigated from 'Workspace'

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/ngx-dashboard#133]
**Steps to Reproduce**

1. Create a Tale
2. Add data to the Workspace
3. Click 'External Data'

**Expected Results**

I expected to see the message about there not being any external data, along with a request to girder that fetches that info.

**Actual Results**

Instead, I didn't see the request get sent out and the UI didn't update.

**NOTES**

After the testing steps above, click on the 'Home' tab and then click back to 'External Data' and you'll see the expected behavior.

![YJVbXTP3LA](https://user-images.githubusercontent.com/9289652/105899689-d452d780-5fcf-11eb-89de-1105e2109700.gif)

**Comment by Xarthisius** [comment]
Couldn't reproduce with latest ngx-dashboard. Please reopen if issue persists.
