### ISSUE TITLE
Missing and inconsistent fields on metadata page 

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#142]
The view and edit modes of the metadata page have inconsistent fields and display order between the view and edit modes. Also, the metadata page is missing fields that are in the v0.9 interface.  This is likely caused by inconsistencies in the mockups.

* View mode displays "Tale ID" and "Involatile Data" while edit mode does not include Tale ID and displays "Datasets Used" as citations. At some point we decided not to display the ID or Involatile Data in the previous interface.
* View mode displays related identifiers, edit mode does not
* Fields are in a different order in view mode while edit is consistent with v0.9. I think view mode should be consistent with edit mode.

**Comment by Xarthisius** [comment]
Just for future reference:

![dash](https://user-images.githubusercontent.com/352673/110536566-3a5e6e80-80e7-11eb-8410-40261f54df14.png)

**Comment by bodom0015** [comment]
* New field order
        * Title
        * (Read-only) Created By
        * Authors
        * Category
        * Environment
        * License
        * Description
        * Illustration
        * (Read-only) Datasets Used
        * (Read-only/conditional) Related Identifiers
        * (Read-only) Published Location
        * (Read-only) Date Created
        * (Read-only) Last Updated
