### ISSUE TITLE
'Tale History > [...] > View Info' should render Tale metadata instead of raw version folder

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#144]
**Expected Results**

![after](https://user-images.githubusercontent.com/352673/110674989-0b540580-8198-11eb-84e3-df96daf1fea4.png)

**Actual Results**

![before](https://user-images.githubusercontent.com/352673/110674997-0f802300-8198-11eb-9489-59ec4c931807.png)

**NOTES**

I'll be adding `GET /tale/:id/restore?versionId=...` for that purpose. It will return "restored" Tale without actually performing any action.

**Comment by bodom0015** [comment]
Did this functionality ever get implemented? I think the existing `/restore` endpoint actually performs the restoration, but a `dryRun=true` parameter or similar might be an easy way to signal this.

Or expand `GET /tale` to include an optional `?versionId` parameter. This would allow us to query for a Tale's metadata given a particular version.

**Comment by Xarthisius** [comment]
@bodom0015 yeah, it's been waiting for its UI counterpart here: https://github.com/whole-tale/wt_versioning/pull/24

**Comment by bodom0015** [comment]
Ah, apologies... I did not realize there was an open PR for the API side already. Will take a look :+1: thank you!
