### ISSUE TITLE
Menu items enabled for read-only tale

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#153]
**Problem:**
When viewing a read-only tale, several menu options are enabled that should require write permissions. I *think* Duplicate, Export, Full Screen and Docs should be the only ones enabled.

**Test case:**
1. Login to https://dashboard.stage.wholetale.org
2. Open "Public Tales" > "LIGO Tale"
3. Select the "..." menu

**Expected results:**
Rebuild, Restart, Save version, Publish, and Connect to Git repo should be disabled.

**Actual results:**
Rebuild, Restart, Save version, Publish, Connect to Git are all enabled.

**Comment by bodom0015** [comment]
Should these entries simply be disabled, or should they be hidden entirely?

I think the logic should be similar both ways, just asking for clarification.

**Comment by craig-willis** [comment]
On the version panel, the menu items are hidden.  For consistency, I'd go with that.
