### ISSUE TITLE
Files in the file browser fill all available space (chrome 91.x)

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#200]
Something has changed in chrome and it affects our file browser. If you add a single file, the row with it spans over entire available area, e.g:

![wt](https://user-images.githubusercontent.com/352673/120371903-1bcdd500-c2dc-11eb-87a2-210d95d014fa.png)

Left panel: Chromium Version 90.0.4430.93 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
Right panel: Google Chrome Version 91.0.4472.77 (Official Build) (64-bit)

**Comment by craig-willis** [comment]
I just updated on MacOS (91.0.4472.77) and am seeing the same thing.
