### ISSUE TITLE
[Draft] Export recorded run

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#202]
**Requirements:**
* The user must be able to export a specific recorded run
* There's no mockup for this, but it should work like export on version menu

See https://github.com/whole-tale/girder_wholetale/issues/494

**Comment by bodom0015** [comment]
Linking this to #128, possible duplicate?

**Comment by craig-willis** [comment]
Already covered by https://github.com/whole-tale/ngx-dashboard/pull/303
