### ISSUE TITLE
[Draft] Publish recorded run

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#203]
**Requirements:**
* The user must be able to publish a specific recorded run
* Note: There's no mockup for this and we haven't implemented this for versions, but could be added as a menu item on the run/version menu.

**Comment by bodom0015** [comment]
Forgive me if this has already been answered before.. for clarity, is this in addition to our existing publish options?

Or would this replace the existing "Publish Tale" functionality to instead publish the current version of the Tale?

**Comment by craig-willis** [comment]
Replaced by https://github.com/whole-tale/ngx-dashboard/issues/314
