### ISSUE TITLE
tale-sharing-tab shows blank/broken image when gravatar_baseurl is not set

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/ngx-dashboard#232]
Cases where `gravatar_baseurl` is not set on a user causes a blank image to be shown in the tale-sharing tab.

This is handled correctly in the navbar (see https://github.com/whole-tale/ngx-dashboard/blob/master/src/app/layout/header.component.html#L22-L23), but there is no default image set for the tale-sharing tab.

My suggestion would be to use either use a generic "user" icon or simply use the WT logo (e.g. https://avatars.githubusercontent.com/u/13108471?s=200&v=4)

**Comment by Xarthisius** [comment]
The only situation when `gravatar_baseUrl` is not set is during creation an account without an email, which I think is not possible?

**Comment by bodom0015** [comment]
Answered this on the dev call, but for completeness' sake: this has only been seen with the Admin user

**Comment by bodom0015** [comment]
Closing this for now, as it is not easily reproducible
