### ISSUE TITLE
Tale Versioning improvements

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/ngx-dashboard#234]
Found during review of #205

* Renaming a version changes order in history panel (should be based on created date instead?)
* Renamed version is not reflected in "Run based on "
* Link to version from "Run based on..." is nice, can we do the same for the version and run names (i.e., the names link to the version/run in the file browser)?

**Comment by bodom0015** [comment]
Possibly / slightly related to #235

**Comment by bodom0015** [comment]
I have implemented the first and third points here, but our current `SyncService` is missing a signal / implementation for what to do if/when a version is updated or added. We signal when the Tale changes, but not individual versions.

@craig-willis @Xarthisius any idea if the backend will send a signal when a version is updated?

**Comment by craig-willis** [comment]
I believe the `wt_tale_updated` event is sent in all cases.  The versions in the history panel updates for me on add, delete and rename, but the "Based on version..." doesn't.  In the following, I renamed the version from the default name to "v1" and the version name updated in the history panel:

<img width="324" alt="Screen Shot 2022-01-31 at 9 49 55 AM" src="https://user-images.githubusercontent.com/4334350/151815115-eb51a852-1822-4ff2-95bc-9b69e131c0dd.png">
