### ISSUE TITLE
Odd dropdown behavior on Run > Files

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/ngx-dashboard#235]
* Dropdown for in Tale > Files > Versions > <some_version> > "v" disappears almost immediately after click, which makes e.g renaming version close to impossible

**Steps to Reproduce**
1. Navigate to Run Tale > Files > Home
2. Upload a file or create a folder, if necessary
3. Expand the dropdown to the right of one of the items in the list
     * You should see a dropdown menu appear
 
**Expected Results**
* Dropdown menu stays open until user clicks elsewhere or chooses an item in the list

**Actual Results**
* Dropdown menu automatically closes after 1-2 seconds

**Comment by craig-willis** [comment]
Nudging this issue. This seems to still be a problem.
