### ISSUE TITLE
[View > Metadata > Edit] License dropdown is not populated

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#24]
**Steps to Reproduce**
1. Deploy and create a new Tale
1. Navigate to View > Metadata. Hit Edit button.
1. Select `License` field

**Expected Results**
Dropdown with prepopulated entries

**Actual Results**
Text field

**NOTES**
There are two accepted values: 
* CC0-1.0
* CC-BY-4.0

**Comment by bodom0015** [comment]
This should be fixed on `master`: https://github.com/whole-tale/ngx-dashboard/commit/f86d741cffa26d47ad2c78b05f217ca2b560d5ab

Feel free to reopen this, if you are encountering errors
