### ISSUE TITLE
[View > Metadata > Edit] Save button provides no feedback

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#25]
**Steps to Reproduce**
1. Deploy and create a new Tale
1. Navigate to View > Metadata. Hit Edit button.
1. Change description, author or anything else.
1. Click save button.

**Expected Results**
Some sort of notification that the Tales has been updated successfully.

**Actual Results**
Seemingly nothing happens

**Comment by craig-willis** [comment]
I'm seeing a "Tale save successfully" toast since rebuilding.

**Comment by bodom0015** [comment]
This should be fixed on master. @Xarthisius  if you're still seeing issues with the toasts appearing, fell free to reopen this and I can look into it
