### ISSUE TITLE
Add ability to create a new tale based on a version

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#267]
**Feature request:**
Add the ability to open a version of a tale as a new tale. 

**Source**:

From https://wholetale.slack.com/archives/C02FQLTR67P/p1648577005526759:
> Out of curiosity: Saved versions of the Tale can be renamed/deleted/downloaded. Why is "open in a new tale" not an option? It would seem a natural step (emulating the export-to-zenodo-then-re-import-to-WT functionality).
> The functionality is there, just nobody asked for it and wanted a button
> Can I ask for it? That makes n=1...

**Comment by Xarthisius** [comment]
Streamline the following (given `taleId` and `versionId`):

1. POST /tale/{id}/copy : id=`taleId` -> `new_taleId`
2. PUT /tale/{id}/restore : id=`new_taleId`, versionId=`new_versionId`

?
The tricky part is getting `new_versionId`...

**Comment by craig-willis** [comment]
At first glance it seems a little clearer to just do something like:
```
POST /tale/{id}/copy?versionId={version_id}
````
Where the resulting tale contains only the selected version.
