### ISSUE TITLE
Copy on Launch dialog doesn't "run" the Tale

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#27]
**Steps to Reproduce**
1. Deploy and register LIGO
1. *Tale Dashboard* > *Public Tales*: click "Run Tale" on "LIGO Tutorial" and click "Confirm"

**Expected Results**
Tale is copied and launched.

**Actual Results**
Tale is just copied.

**NOTES**
While I'm completely fine with that behavior (and it's my personal preference) I don't know if we collectively agreed on changing that. Either way the wording on the modal should be updated (now it's suggesting launch) or the Tale has to actually launch.

**Comment by craig-willis** [comment]
During my testing, the copy is made but the view remains on "Public Tales". Per the test case, I should be taken to the copy's Run page.

**Comment by bodom0015** [comment]
As of #76, we should now be brought to the copied Tale automatically. I also adjusted the wording of the modal for now as well.

Unless we plan on adding back the other options for "Create + Launch", this issue can probably be closed.
