### ISSUE TITLE
AinWT modal is missing error handling.

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#273]
**Steps to Reproduce**

1. Follow: https://dashboard.stage.wholetale.org/mine?name=AEAREP-3198-Stata&environment=STATA%2016%20%28Desktop%29
2. Click on "Create a new Tale"

**Expected Results**

Tale is created or an error is reported to user. In this case: `POST /tale/import` yields 400 and:

```
{"message": "You need to provide either :  1) a zipfile with an exported Tale or  2) a url to a Tale or  3) both 'imageId' and 'url' parameters.", "type": "rest"}
```

**Actual Results**

Seemingly nothing happens.

**NOTES**

What error message suggests is not fixable via this modal (you cannot provide the missing url), but we should at least inform user that  action was performed and it failed.

**Comment by bodom0015** [comment]
Fixed by #279
