### ISSUE TITLE
[View > Files > External Data] nothing shows up

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#28]
**Steps to Reproduce**
1. Deploy and register LIGO Tale
1. *Tale Dashboard* > *Public Tales*: click "View" on "LIGO Tutorial"
1. Navigate to *Files* > *External Data*

**Expected Results**
See the content of the Tale's `dataSet`.

**Actual Results**
Panel is empty.

**Comment by bodom0015** [comment]
There appears to be some error in registering the LIGO HTTPS resources. Performing a GET against the `/dataset` endpoint does not yield any of the expected LIGO datasets that should have been registered by `python ./register_ligo.py`:
```json
  {
    "_id": "5ecf0070d0abc71e296340a0",
    "_modelType": "folder",
    "created": "2020-05-28T00:06:08.145000+00:00",
    "creatorId": "5ec313fc88049a867e342730",
    "description": "",
    "identifier": "https://www.gw-openscience.org",
    "name": "www.gw-openscience.org",
    "provider": "HTTPS",
    "size": 0,
    "updated": "2020-05-28T00:06:12.469000+00:00"
  }
```

Could this possibly be the same issue as https://github.com/whole-tale/girder_wholetale/issues/304?

**Comment by Xarthisius** [comment]
I don't think `/dataset` is relevant here. Data Catalog in Whole Tale is a nested structure and objects in Tale's `dataSet` can be added from within the Catalog hierarchy. Therefore they may not appear in neither `/dataset?myData=False`, nor `/dataset?myData=True` and LIGO is actually a good example of that. I'll comment on whole-tale/girder_wholetale#304 why it's an expected behavior.

After a successful deployment, you can verify the validity of the LIGO Tale (and its dataset) in a three ways:
1. Run the tale and using a terminal in jupyter call `ls ../data`
1. Using Girder's swagger run `GET /tale/{id}` and see if `dataSet` is populated. It should look roughly like this:
   ```
   {
      "_accessLevel": 0,
      "_id": "5ecf8956192e6e339a473873",
      "_modelType": "tale",
      "authors": [
         {
           "firstName": "Kacper",
           "lastName": "Kowalik",
           "orcid": "https://orcid.org/0000-0003-1709-3744"
         }
       ],
      ...
      "dataSet": [
         {
           "_modelType": "item",
           "itemId": "5ecf8950192e6e339a473855",
           "mountPath": "BBH_events_v3.json"
         },
         {
           "_modelType": "item",
           "itemId": "5ecf8950192e6e339a473858",
           "mountPath": "GW150914_4_template.hdf5"
         }
         ...
    ```
1. Go to [View > Files > External Data] using old dashboard.
