### ISSUE TITLE
User not prompted to login when accessing interact tab for public tale.

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#296]
**Steps to Reproduce**
Encountered when testing https://github.com/whole-tale/ngx-dashboard/pull/295
1. Login to dashboard.
1. Create a Tale, make it public. Navigate to view / interact tab.
1. Copy the url.
1. Logout.
1. In an incognito session: open the url from 3.

**Expected Results**
Forced to login and afterwards on the proper interact tab.

**Actual Results**
"You must Run this Tale before you can Interact" message appears.

**NOTES**
* I'm not 100% sure what the behavior should be here. Prompting to login makes sense, but so would a message that says "You must login to run this tale. As it is, we offer only a tooltip on the run button to tell the user they need to login.
* I noticed that `tab=sharing` briefly shows the Sharing tab content before redirecting to login.

**Comment by bodom0015** [comment]
I'm not sure what the right way to handle this would be.. If the user is not logged in, then the Interact tab does not appear and is not clickable in the view. The user can still end up on Interact directly in that case using the URL, but I would not expect that to be a common pattern that they're utilizing.

The `tab=interact` usually fetches from /api/v1/instance (just like `tab=sharing` fetches a list of all users in the system), but it becomes a no-op if the user is not logged in. Removing this check causes the sharing and interact tabs to behave the same - if a user is not logged in, their API requests fail with a 401 and force the user through login.

I can also go ahead and add the following to the Interact page just in case the user does somehow end up in this situation and that somehow redirect fails:
```html

    <!-- User is not logged in -->
    <div class="sixteen wide column" *ngIf="!tokenService?.user?.value">
      <div class="status-banner">
        <h3>You must Sign In before you can Interact.</h3>
      </div>
    </div>
```
