### ISSUE TITLE
Context menu doesn't display after rename

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#297]
**Steps to Reproduce**
1. Create a new tale
2. Create folder "folder1"
3. Rename folder to "folder2"
4. Open context menu for folder

**Expected Results**

Context menu displays

**Actual Results**

Context menu doesn't display

**NOTES**
* Chrome Version 104.0.5112.101/MacOS 
* In the console I sometimes see an error "Transition: Element is no longer attached to DOM. Unable to animate"
* For me, sometimes step 2 folder doesn't appear without refresh
* This also happens for files

**Comment by bodom0015** [comment]
Possible regression of #259
