### ISSUE TITLE
Return-route for non-logged in users not working

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#34]
**Steps to Reproduce**
1. Open incognito window or logout from dashboard
2. Go to https://dashboard.local.wholetale.org/datasets
3. Select "Access Whole Tale" and login if needed

**Expected Results**
I should be taken to https://dashboard.local.wholetale.org/datasets after login. This should happen for any non-default route.

**Actual Results**
I'm taken to the default landing page https://dashboard.local.wholetale.org/public

**Notes**
I'm working through the standard test plan (https://github.com/whole-tale/wt-design-docs/issues/137)

**Comment by craig-willis** [comment]
Still a problem in https://github.com/whole-tale/ngx-dashboard/commit/6d9d4e304a9907ee54c64966f58719db87a70ca9

**Comment by cyberdante** [comment]
This needs an auth guard to protect the existing routes and verify whether there is a logged user attempting to navigate to a certain route.
