### ISSUE TITLE
"Move to" on a file yields error

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#40]
**Steps to Reproduce**
1. Create a Tale
1. Navigate to *View* > *Files* > *Home*.
1. Using `(+)` upload a file.
1. Using action menu on the file, select and click "Move to"

**Expected Results**
Move modal opens

**Actual Results**
`"Cannot read property '_id' of undefined" ` pops up

**Comment by bodom0015** [comment]
I believe that this is actually the same issue as #37, and should be fixed as a part of #78 

I may need to dig into it a bit more to be sure
