### ISSUE TITLE
No indication of data registration progress

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/ngx-dashboard#43]
**Steps to Reproduce**
1. 10.5065/D6862DM8

**Expected results**
Some indication of registration progress (old UI had toasts?)

**Actual results**
No indication of registration progress

**Notes**
Part of me would prefer something like a dismissible publish progress over the toasts.  I know we talk about things that take ages to register, but for most cases I'd be happy to wait to add it until register is complete.

**Comment by Xarthisius** [comment]
Potentially depends on / is fixed by https://github.com/whole-tale/girder_wholetale/pull/326
