### ISSUE TITLE
Excessive spacing in the select-data modal's tree hierarchy

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#90]
Bug found during testing of #78. Not a blocker, I'm just noting it so I won't forget.

**Steps to Reproduce**
1. Deploy #78 and register Ligo Tale
1. Create a Tale
1. Navigate View Tale > Files > External Data
1. Click (+) / WT Data Catalog
1. In the `Select from WT External Data Catalog` select `WT Catalog` from the outer left panel, then in the inner left panel double-click on `www.gw-openscience.org`

**Expected Results**
Nicely formated tree showing folder named `s`

**Actual Results**
![wt](https://user-images.githubusercontent.com/352673/90663321-1ef54a00-e20f-11ea-9e90-4ae14affc581.png)

**NOTES**
Tested both on Chrome and Firefox. Looks the same.

**Comment by bodom0015** [comment]
Interesting... I believe this is related to https://github.com/whole-tale/girder_wholetale/issues/304, because I am also seeing this behavior on each of the resources with URLs.

Still looking into where the extra space is coming from
