### ISSUE TITLE
Remove an option to name dataset in data registration modal

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/ngx-dashboard#93]
Right now the field `Folder Name` in the data registration modal is completely ignored. That's actually a very good thing. We should simply drop it.

![wt2](https://user-images.githubusercontent.com/352673/90666264-be680c00-e212-11ea-9364-aec59770fb93.png)

**Steps to Reproduce**
1. Login to the WholeTale Dashboard
1. Create a Tale navigate to the Run > External Data view
1. Click (+), and choose "Web (DOI or URL)"
  - The data registration modal should open
  - Enter 10.5065/D6862DM8 and search

**Expected Results**
`Folder Name` gone.

**Actual Results**
See image above

**Comment by bodom0015** [comment]
This was an artifact of the previous EmberJS dashboard..
Its function was never clear, and I am happy to get rid of it :+1:
