### ISSUE TITLE
Published location not changing across publishing events

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/ngx-dashboard#95]
**Steps to Reproduce**
1. Open a Tale that is ready to publish (at least 1 file, an author, and a description)
2. Connect to DataONE Dev & Zenodo Sandbox
3. Publish to DataONE
4. Publish Zenodo

**Expected Results**
After step 4, I expected to see the `Identifier` label in the model show the identifier of the latest doi. In the image below you can see that although the Tale was published to Zenodo, the DataONE doi is showen
<img width="992" alt="Screen Shot 2020-08-26 at 4 36 20 PM" src="https://user-images.githubusercontent.com/9289652/91367344-04951080-e7bb-11ea-9e61-7de471023a49.png">

**Actual Results**
The Identifier from the first publish event is shown.

**Comment by ThomasThelen** [comment]
This is in part due to us updating `publishInfo` records vs of appending when updating a dataset in Zenodo, seen [here](https://github.com/whole-tale/gwvolman/blob/master/gwvolman/lib/zenodo.py#L377). I didn't reference this when writing the Tale updating portion for DataONE, but can certainly bring parity there.

We haven't described a convention about the ordering of information in the Tale's publishInfo array; I like the idea of keeping each record of a publish event for that Tale so that the complete publishing provenance is easy to see (it's of course possible to visit Zenodo or DataONE and find out which packages were updated). As for `publishInfo` being an ordered set, it certainly has utility to say `publishInfo[-1]` to get the last publishing info-but it's also possible to sort by date. Any thoughts on this @Xarthisius or @bodom0015?

**Comment by bodom0015** [comment]
This is likely a bad assumption on my part.. I think I have been assuming that the first item in the array would be the most recent. It may have supposed to have been the last item instead, so I should have checked how this was handled in the old dashboard.

@Xarthisius Is it safe to that the last item in the publishInfo array is the most recent, or is there perhaps a better pattern for this?

**Comment by ThomasThelen** [comment]
Because we update zenodo records rather than push to the back with each update, it's not safe to assume that the last element is the latest. For example,
1. Publish to zenodo (new record is pushed into the array)
2. Publish to DataONE (new record is pushed into the array)
3. Publish back to zenodo (first record is updated, DataONE record is still the last element)
