### ISSUE TITLE
Data Catalog -> Add Data modal not opening

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/ngx-dashboard#97]
It looks like the data registration modal isn't hooked up to the Data Catalog page yet; creating this issue so that we don't forget.

**Steps to Reproduce**
1. Open the dashboard
2. Navigate to the `Data Catalog` page
3. Click `Add Data +`

**Expected Results**
The data registration modal to open

**Actual Results**
Nothing happens

**Comment by bodom0015** [comment]
The Data Catalog view is currently a placeholder, as is "Compute Environments". These navs just contain static data and should likely be hidden for now, as I believe they were initially out-of-scope for the Angular migration.
